name: Publish release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: chmod +x ./ImageCropper/gradlew -Pversion=${{ github.event.release.tag_name }} -Pghargs='skd.repo.username=${{secrets.SKD_REPO_USERNAME}},skd.repo.password=${{secrets.SKD_REPO_PASSWORD}},skd.mrepo.username=${{secrets.SKD_MREPO_USERNAME}},skd.mrepo.password=${{secrets.SKD_MREPO_PASSWORD}}'   build publish
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ github.token }}
